In [1]:
#importing libraries
import numpy as np
import pandas as pd

In [2]:
#loading data
dataset = pd.read_csv('houses.csv')

#showing data
dataset.head(20)

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,price
0,3.0,1.00,1180.0,5650.0,1.0,0.0,0.0,3.0,7.0,1180.0,0.0,1955.0,0.0,98178.0,47.5112,-122.257,1340.0,22.190
1,3.0,2.25,2570.0,7242.0,2.0,0.0,0.0,3.0,7.0,2170.0,400.0,1951.0,1991.0,98125.0,47.7210,-122.319,1690.0,53.800
2,2.0,1.00,770.0,10000.0,1.0,0.0,0.0,3.0,6.0,770.0,0.0,1933.0,0.0,98028.0,47.7379,-122.233,2720.0,18.000
3,4.0,3.00,1960.0,5000.0,1.0,0.0,0.0,5.0,7.0,1050.0,910.0,1965.0,0.0,98136.0,47.5208,-122.393,1360.0,60.400
4,3.0,2.00,1680.0,8080.0,1.0,0.0,0.0,3.0,8.0,1680.0,0.0,1987.0,0.0,98074.0,47.6168,-122.045,1800.0,51.000
5,4.0,4.50,5420.0,101930.0,1.0,0.0,0.0,3.0,11.0,3890.0,1530.0,2001.0,0.0,98053.0,47.6561,-122.005,4760.0,123.000
6,3.0,2.25,1715.0,6819.0,2.0,0.0,0.0,3.0,7.0,1715.0,0.0,1995.0,0.0,98003.0,47.3097,-122.327,2238.0,25.750
7,3.0,1.50,1060.0,9711.0,1.0,0.0,0.0,3.0,7.0,1060.0,0.0,1963.0,0.0,98198.0,47.4095,-122.315,1650.0,29.185
8,3.0,1.00,1780.0,7470.0,1.0,0.0,0.0,3.0,7.0,1050.0,730.0,1960.0,0.0,98146.0,47.5123,-122.337,1780.0,22.950
9,3.0,2.50,1890.0,6560.0,2.0,0.0,0.0,3.0,7.0,1890.0,0.0,2003.0,0.0,98038.0,47.3684,-122.031,2390.0,32.300
10,3.0,2.50,3560.0,9796.0,1.0,0.0,0.0,3.0,8.0,1860.0,1700.0,1965.0,0.0,98007.0,47.6007,-122.145,2210.0,66.250
11,2.0,1.00,1160.0,6000.0,1.0,0.0,0.0,4.0,7.0,860.0,300.0,1942.0,0.0,98115.0,47.6900,-122.292,1330.0,46.800
12,3.0,1.00,1430.0,19901.0,1.5,0.0,0.0,4.0,7.0,1430.0,0.0,1927.0,0.0,98028.0,47.7558,-122.229,1780.0,31.000
13,3.0,1.75,1370.0,9680.0,1.0,0.0,0.0,4.0,7.0,1370.0,0.0,1977.0,0.0,98074.0,47.6127,-122.045,1370.0,40.000
14,5.0,2.00,1810.0,4850.0,1.5,0.0,0.0,3.0,7.0,1810.0,0.0,1900.0,0.0,98107.0,47.6700,-122.394,1360.0,53.000
15,4.0,3.00,2950.0,5000.0,2.0,0.0,3.0,3.0,9.0,1980.0,970.0,1979.0,0.0,98126.0,47.5714,-122.375,2140.0,65.000
16,3.0,2.00,1890.0,14040.0,2.0,0.0,0.0,3.0,7.0,1890.0,0.0,1994.0,0.0,98019.0,47.7277,-121.962,1890.0,39.500
17,4.0,1.00,1600.0,4300.0,1.5,0.0,0.0,4.0,7.0,1600.0,0.0,1916.0,0.0,98103.0,47.6648,-122.343,1610.0,48.500
18,2.0,1.00,1200.0,9850.0,1.0,0.0,0.0,4.0,7.0,1200.0,0.0,1921.0,0.0,98002.0,47.3089,-122.210,1060.0,18.900
19,3.0,1.00,1250.0,9774.0,1.0,0.0,0.0,4.0,7.0,1250.0,0.0,1969.0,0.0,98003.0,47.3343,-122.306,1280.0,23.000

In [3]:
#cleaning data "changing nan"
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp = imp.fit(dataset)
dataset = imp.transform(dataset)

In [4]:
#X Data input
X = dataset[:, :-1]
print('X Data is \n' , X[:10])
print('X shape is ' , X.shape)

#y Data output
y = dataset[:, -1]
print('y Data is \n' , y[:10])
print('y shape is ' , y.shape)

X Data is
 [[ 3.00000e+00  1.00000e+00  1.18000e+03  5.65000e+03  1.00000e+00
   0.00000e+00  0.00000e+00  3.00000e+00  7.00000e+00  1.18000e+03
   0.00000e+00  1.95500e+03  0.00000e+00  9.81780e+04  4.75112e+01
  -1.22257e+02  1.34000e+03]
 [ 3.00000e+00  2.25000e+00  2.57000e+03  7.24200e+03  2.00000e+00
   0.00000e+00  0.00000e+00  3.00000e+00  7.00000e+00  2.17000e+03
   4.00000e+02  1.95100e+03  1.99100e+03  9.81250e+04  4.77210e+01
  -1.22319e+02  1.69000e+03]
 [ 2.00000e+00  1.00000e+00  7.70000e+02  1.00000e+04  1.00000e+00
   0.00000e+00  0.00000e+00  3.00000e+00  6.00000e+00  7.70000e+02
   0.00000e+00  1.93300e+03  0.00000e+00  9.80280e+04  4.77379e+01
  -1.22233e+02  2.72000e+03]
 [ 4.00000e+00  3.00000e+00  1.96000e+03  5.00000e+03  1.00000e+00
   0.00000e+00  0.00000e+00  5.00000e+00  7.00000e+00  1.05000e+03
   9.10000e+02  1.96500e+03  0.00000e+00  9.81360e+04  4.75208e+01
  -1.22393e+02  1.36000e+03]
 [ 3.00000e+00  2.00000e+00  1.68000e+03  8.08000e+03  1.00000e+00
   0.00000e+00  0.00000e+00  3.00000e+00  8.00000e+00  1.68000e+03
   0.00000e+00  1.98700e+03  0.00000e+00  9.80740e+04  4.76168e+01
  -1.22045e+02  1.80000e+03]
 [ 4.00000e+00  4.50000e+00  5.42000e+03  1.01930e+05  1.00000e+00
   0.00000e+00  0.00000e+00  3.00000e+00  1.10000e+01  3.89000e+03
   1.53000e+03  2.00100e+03  0.00000e+00  9.80530e+04  4.76561e+01
  -1.22005e+02  4.76000e+03]
 [ 3.00000e+00  2.25000e+00  1.71500e+03  6.81900e+03  2.00000e+00
   0.00000e+00  0.00000e+00  3.00000e+00  7.00000e+00  1.71500e+03
   0.00000e+00  1.99500e+03  0.00000e+00  9.80030e+04  4.73097e+01
  -1.22327e+02  2.23800e+03]
 [ 3.00000e+00  1.50000e+00  1.06000e+03  9.71100e+03  1.00000e+00
   0.00000e+00  0.00000e+00  3.00000e+00  7.00000e+00  1.06000e+03
   0.00000e+00  1.96300e+03  0.00000e+00  9.81980e+04  4.74095e+01
  -1.22315e+02  1.65000e+03]
 [ 3.00000e+00  1.00000e+00  1.78000e+03  7.47000e+03  1.00000e+00
   0.00000e+00  0.00000e+00  3.00000e+00  7.00000e+00  1.05000e+03
   7.30000e+02  1.96000e+03  0.00000e+00  9.81460e+04  4.75123e+01
  -1.22337e+02  1.78000e+03]
 [ 3.00000e+00  2.50000e+00  1.89000e+03  6.56000e+03  2.00000e+00
   0.00000e+00  0.00000e+00  3.00000e+00  7.00000e+00  1.89000e+03
   0.00000e+00  2.00300e+03  0.00000e+00  9.80380e+04  4.73684e+01
  -1.22031e+02  2.39000e+03]]
X shape is  (1000, 17)
y Data is
 [ 22.19   53.8    18.     60.4    51.    123.     25.75   29.185  22.95
  32.3  ]
y shape is  (1000,)

In [6]:
#Scaling data "rearanging data"
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
print("X after rearanging data\n", X)

X after rearanging data
 [[-4.10268195e-01 -1.44995485e+00 -9.81897913e-01 ... -2.72385899e-01
  -3.55703043e-01 -9.65318233e-01]
 [-4.10268195e-01  2.83121119e-01  5.84365772e-01 ...  1.21117278e+00
  -8.00389282e-01 -4.42971038e-01]
 [-1.58464621e+00 -1.44995485e+00 -1.44388936e+00 ...  1.33067775e+00
  -1.83566434e-01  1.09422214e+00]
 ...
 [-1.58464621e+00 -1.44995485e+00 -1.35374469e+00 ...  8.55486406e-01
  -8.64940510e-01 -1.02501506e+00]
 [-1.58464621e+00 -1.44995485e+00 -1.15091917e+00 ... -1.24398248e+00
   1.07876870e+00 -8.01151972e-01]
 [-2.23820962e-16  1.95399252e-16  1.45661261e-16 ... -2.86378900e-14
   3.35731443e-15 -2.66983440e-17]]

In [7]:
#Splitting data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

#Splitted Data
print('X_train shape is ' , X_train.shape)
print('X_test shape is ' , X_test.shape)
print('y_train shape is ' , y_train.shape)
print('y_test shape is ' , y_test.shape)

X_train shape is  (670, 17)
X_test shape is  (330, 17)
y_train shape is  (670,)
y_test shape is  (330,)

In [17]:
#Applying KNeighborsRegressor Model
'''
#sklearn.neighbors.KNeighborsRegressor(n_neighbors=5, weights=, algorithm=’auto’, leaf_size=30, #n_neighbors= num of used neighbor 
#   p=2, metric=’minkowski’, metric_params=None,n_jobs=None) #weights=distance, or defined function or uniform used to calulate weight
                                                             #algorithm=’auto or ball_tree ,  kd_tree  , brute

'''

from sklearn import neighbors #K Neighbors Regressor
knn = neighbors.KNeighborsRegressor(n_neighbors = 4)
y_ = knn.fit(X_train, y_train)

#Calculating Details
print('KNeighborsRegressorModel Train Score is : ' , y_.score(X_train, y_train)) #accurancy for training data
print('KNeighborsRegressorModel Test Score is : ' , y_.score(X_test, y_test)) #accurancy foor testing

KNeighborsRegressorModel Train Score is :  0.8292910346342809
KNeighborsRegressorModel Test Score is :  0.7307537281104751

In [18]:
#Calculating Prediction
y_pred = knn.predict(X_test) 
print('Predicted Value for KNeighborsRegressorModel is : \n' , y_pred[:10])

#calcylating actual output
print('Actual Value for KNeighborsRegressorModel is : \n' , y_test[:10])

Predicted Value for KNeighborsRegressorModel is :
 [30.9625  62.75    34.32125 27.75    26.51225 44.62375 42.8125  40.45
 23.1275  28.3375 ]
Actual Value for KNeighborsRegressorModel is :
 [19.     60.5    36.     26.99   51.7534 47.85   55.995  29.     16.66
 22.    ]

In [20]:
#calculating errors for regression model
#Calculating Mean Absolute Error
from sklearn.metrics import mean_absolute_error 
MAEValue = mean_absolute_error(y_test, y_pred, multioutput='uniform_average') # it can be raw_values
print('Mean Absolute Error Value is : ', MAEValue)

#----------------------------------------------------
#Calculating Mean Squared Error
from sklearn.metrics import mean_squared_error
MSEValue = mean_squared_error(y_test, y_pred, multioutput='uniform_average') # it can be raw_values
print('Mean Squared Error Value is : ', MSEValue)

#----------------------------------------------------
#Calculating Median Squared Error
from sklearn.metrics import median_absolute_error
MdSEValue = median_absolute_error(y_test, y_pred)
print('Median Squared Error Value is : ', MdSEValue )

Mean Absolute Error Value is :  9.282359090909091
Mean Squared Error Value is :  249.4835894858409
Median Squared Error Value is :  5.603374999999996